const WritingSystem = {
    Abugida: "Abugida",
    Alphabet: "Alphabet",
    Abjad: "Abjad",
    Syllabary: "Syllabary",
    Alphasyllabary: "Alphasyllabary",
    Logosyllabary: "Logosyllabary",
    Semisyllabary: "Semisyllabary",
    Pictography: "Pictography",
}

export const glyphInfo = {
    glyph_0_n7: { // ఒ
        codePoint: 0x0C12,
        writingSystem: WritingSystem.Abugida,
        script: 'Telugu',
        language: 'Telugu',
    },
    glyph_0_n6: { // श
        codePoint: 0x0936,
        writingSystem: WritingSystem.Abugida,
        script: 'Devanagari',
        language: 'Nepali',
    },
    glyph_0_n5: { // ꊛ
        codePoint: 0xa29b,
        writingSystem: WritingSystem.Syllabary,
        script: 'Yi',
        language: 'Mantsi',
    },
    glyph_0_n4: { // R
        codePoint: 0x52,
        writingSystem: WritingSystem.Alphabet,
        script: 'Latin',
        language: 'Spanish',
    },
    glyph_0_n3: { // 😊
        codePoint: 0x1f60a,
        writingSystem: WritingSystem.Pictography,
        script: "Emoji",
        language: null,
    },
    glyph_0_n2: { // Я
        codePoint: 0x42f,
        writingSystem: WritingSystem.Alphabet,
        script: "Cyrillic",
        language: 'Bulgarian',
    },
    glyph_0_n1: { // ࠌ
        codePoint: 0x80c,
        writingSystem: WritingSystem.Abjad,
        script: "Samaritan",
        language: 'Samaritan Hebrew',
    },
    glyph_0_0: { // ฒ
        codePoint: 0xe12,
        writingSystem: WritingSystem.Abugida,
        script: 'Thai',
        language: 'Thai',
    },
    glyph_0_p1: { // ࡂ
        codePoint: 0x842,
        writingSystem: WritingSystem.Alphabet,
        script: 'Mandaic',
        language: 'Mandaic',
    },
    glyph_0_p2: { // キ
        codePoint: 0x30ad,
        writingSystem: WritingSystem.Syllabary,
        script: 'Katakana',
        language: 'Japanese',
    },
    glyph_0_p3: { // Л
        codePoint: 0x41b,
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Kyrgyz',
    },
    glyph_0_p4: { // რ
        codePoint: 0x10e0,
        writingSystem: WritingSystem.Alphabet,
        script: 'Georgian',
        language: 'Georgian',
    },
    glyph_0_p5: { // ޝ
        codePoint: 0x79d,
        writingSystem: WritingSystem.Abugida,
        script: 'Thaana',
        language: 'Maldivian',
    },
    glyph_0_p6: { // அ
        codePoint: 0xb85,
        writingSystem: WritingSystem.Abugida,
        script: 'Tamil',
        language: 'Tamil',
    },
    glyph_0_p7: { // H
        codePoint: 0x48,
        writingSystem: WritingSystem.Alphabet,
        script: 'Latin',
        language: 'Tok Pisin',
    },
    glyph_1_n7: { // ङ
        codePoint: 0x919,
        writingSystem: WritingSystem.Abugida,
        script: 'Devanagari',
        language: 'Newar',
    },
    glyph_1_n6: { // ถ
        codePoint: 0xe16,
        writingSystem: WritingSystem.Abugida,
        script: 'Thai',
        language: 'Tai Yo',
    },
    glyph_1_n5: { // ዑ
        codePoint: 0x12d1,
        writingSystem: WritingSystem.Abugida,
        script: "Ge'ez",
        language: 'Amharic',
    },
    glyph_1_n4: { // क
        codePoint: 0x915,
        writingSystem: WritingSystem.Abugida,
        script: 'Devanagari',
        language: 'Hindi',
    },
    glyph_1_n3: { // ဟ
        codePoint: 0x101f,
        writingSystem: WritingSystem.Abjad,
        script: 'Burmese',
        language: 'Burmese',
    },
    glyph_1_n2: { // ꚸ
        codePoint: 0xa6b8,
        writingSystem: WritingSystem.Syllabary,
        script: 'Bamum',
        language: 'Bamum',
    },
    glyph_1_n1: { // ᐊ
        codePoint: 0x140a,
        writingSystem: WritingSystem.Abugida,
        script: 'Qaniujaaqpait',
        language: 'Inuktitut',
    },
    glyph_1_0: { // ᐃ
        codePoint: 0x1403,
        writingSystem: WritingSystem.Abugida,
        script: 'Qaniujaaqpait',
        language: 'Inuktitut',
    },
    glyph_1_p1: { // ᐅ
        codePoint: 0x1405,
        writingSystem: WritingSystem.Abugida,
        script: 'Qaniujaaqpait',
        language: 'Inuktitut',
    },
    glyph_1_p2: { // উ
        codePoint: 0x989,
        writingSystem: WritingSystem.Abugida,
        script: 'Bengali-Assamese',
        language: 'Bangla',
    },
    glyph_1_p3: { // 區
        codePoint: 0x5340,
        writingSystem: WritingSystem.Logosyllabary,
        script: 'Han',
        language: 'Cantonese',
    },
    glyph_1_p4: { // ܧ
        codePoint: 0x727,
        writingSystem: WritingSystem.Abjad,
        script: 'Syriac',
        language: 'Syriac',
    },
    glyph_1_p5: { // О̄
        codePoint: [0x41e, 0x304],
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Mansi',
    },
    glyph_1_p6: { // 𞋢
        codePoint: 0x1e2e2,
        writingSystem: WritingSystem.Alphabet,
        script: 'Wancho',
        language: 'Wancho',
    },
    glyph_1_p7: { // ひ
        codePoint: 0x3072,
        writingSystem: WritingSystem.Syllabary,
        script: 'Hiragana',
        language: 'Japanese',
    },
    glyph_2_n7: { // ⻩
        codePoint: 0x2ee9,
        writingSystem: WritingSystem.Logosyllabary,
        script: 'Han',
        language: 'Japanese',
    },
    glyph_2_n6: { // Ψ
        codePoint: 0x3a8,
        writingSystem: WritingSystem.Alphabet,
        script: 'Greek',
        language: 'Greek',
    },
    glyph_2_n5: { // 𖩏
        codePoint: 0x16a4f,
        writingSystem: WritingSystem.Alphabet,
        script: 'Mru',
        language: 'Mru',
    },
    glyph_2_n4: { // 𐒾
        codePoint: 0x104be,
        writingSystem: WritingSystem.Alphabet,
        script: 'Osage',
        language: 'Osage',
    },
    glyph_2_n3: { // む
        codePoint: 0x3080,
        writingSystem: WritingSystem.Syllabary,
        script: 'Hiragana',
        language: 'Japanese',
    },
    glyph_2_n2: { // ꂃ
        codePoint: 0xa083,
        writingSystem: WritingSystem.Syllabary,
        script: 'Yi',
        language: 'Nuosu',
    },
    glyph_2_n1: { // 语
        codePoint: 0x8bed,
        writingSystem: WritingSystem.Logosyllabary,
        script: 'Han',
        language: 'Mandarin',
    },
    glyph_2_0: { // 🤩
        codePoint: 0x1f929,
        writingSystem: WritingSystem.Pictography,
        script: 'Emoji',
        language: null,
    },
    glyph_2_p1: { // Å
        codePoint: 0xc5,
        writingSystem: WritingSystem.Alphabet,
        script: 'Latin',
        language: 'Swedish',
    },
    glyph_2_p2: { // Ҵ
        codePoint: 0x4b4,
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Abkhaz',
    },
    glyph_2_p3: { // 𑐂
        codePoint: 0x11402,
        writingSystem: WritingSystem.Abugida,
        script: 'Newa',
        language: 'Newar',
    },
    glyph_2_p4: { // 겅
        codePoint: 0xac85,
        writingSystem: WritingSystem.Alphasyllabary,
        script: 'Hangeul',
        language: 'Korean',
    },
    glyph_2_p5: { // 𐒌
        codePoint: 0x1048c,
        writingSystem: WritingSystem.Alphabet,
        script: 'Osmanya',
        language: 'Somali',
    },
    glyph_2_p6: { // ଞ
        codePoint: 0xb1e,
        writingSystem: WritingSystem.Abugida,
        script: 'Odia',
        language: 'Odia',
    },
    glyph_2_p7: { // ꂹ
        codePoint: 0xa0b9,
        writingSystem: WritingSystem.Syllabary,
        script: 'Yi',
        language: 'Nuosu',
    },
    glyph_2_p8: { // າ
        codePoint: 0xeb2,
        writingSystem: WritingSystem.Abugida,
        script: 'Lao',
        language: 'Lao',
    },
    glyph_3_n7: { // ਉ
        codePoint: 0xa09,
        writingSystem: WritingSystem.Abugida,
        script: 'Gurmukhi',
        language: 'Punjabi',
    },
    glyph_3_n6: { // இ
        codePoint: 0xb87,
        writingSystem: WritingSystem.Abugida,
        script: 'Tamil',
        language: 'Tamil',
    },
    glyph_3_n5: { // ߷
        codePoint: 0x7f7,
        writingSystem: WritingSystem.Alphabet,
        script: "N'ko",
        language: "N'ko",
    },
    glyph_3_n4: { // ഋ
        codePoint: 0xd0b,
        writingSystem: WritingSystem.Abugida,
        script: 'Malayalam',
        language: 'Malayalam',
    },
    glyph_3_n3: { // 𖼒
        codePoint: 0x16f12,
        writingSystem: WritingSystem.Abugida,
        script: 'Miao',
        language: 'A-Hmao',
    },
    glyph_3_n2: { // ㄖ
        codePoint: 0x3116,
        writingSystem: WritingSystem.Semisyllabary,
        script: 'Bopomofo',
        language: 'Mandarin',
    },
    glyph_3_n1: { // ق
        codePoint: 0x642,
        writingSystem: WritingSystem.Abjad,
        script: 'Arabic',
        language: 'Arabic',
    },
    glyph_3_0: { // Ҩ
        codePoint: 0x0,
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Abkhaz',
    },
    glyph_3_p1: { // ឈ
        codePoint: 0x1788,
        writingSystem: WritingSystem.Abugida,
        script: 'Khmer',
        language: 'Khmer',
    },
    glyph_3_p2: { // א
        codePoint: 0x5d0,
        writingSystem: WritingSystem.Abjad,
        script: 'Hebrew',
        language: 'Hebrew',
    },
    glyph_3_p3: { // 𞤦
        codePoint: 0x1e926,
        writingSystem: WritingSystem.Alphabet,
        script: 'Adlam',
        language: 'Fulani',
    },
    glyph_3_p4: { // ホ
        codePoint: 0x30db,
        writingSystem: WritingSystem.Syllabary,
        script: 'Katakana',
        language: 'Ainu',
    },
    glyph_3_p5: { // ꓤ
        codePoint: 0xa4e4,
        writingSystem: WritingSystem.Alphabet,
        script: 'Fraser',
        language: 'Lisu',
    },
    glyph_3_p6: { // ᮺ
        codePoint: 0x1bba,
        writingSystem: WritingSystem.Abugida,
        script: 'Sundanese',
        language: 'Sundanese',
    },
    glyph_3_p7: { // 🔥
        codePoint: 0x1f525,
        writingSystem: WritingSystem.Pictography,
        script: 'Emoji',
        language: null,
    },
    glyph_4_n7: { // Џ
        codePoint: 0x40f,
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Serbian',
    },
    glyph_4_n6: { // Ꮊ
        codePoint: 0x13ba,
        writingSystem: WritingSystem.Syllabary,
        script: "Cherokee",
        language: "Cherokee",
    },
    glyph_4_n5: { // ツ
        codePoint: 0x30c4,
        writingSystem: WritingSystem.Syllabary,
        script: "Katakana",
        language: 'Japanese',
    },
    glyph_4_n4: { // ᡲ
        codePoint: 0x1872,
        writingSystem: 'Alphabet',
        script: 'Mongolian',
        language: 'Mongolian',
    },
    glyph_4_n3: { // Ξ
        codePoint: 0x39e,
        writingSystem: WritingSystem.Alphabet,
        script: 'Greek',
        language: 'Greek',
    },
    glyph_4_n2: { // Ѭ
        codePoint: 0x46c,
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Old Church Slavonic',
    },
    glyph_4_n1: { // 𞠊
        codePoint: 0x1e80a,
        writingSystem: WritingSystem.Syllabary,
        script: 'Mende Kikakui',
        language: 'Mende',
    },
    glyph_4_0: { // 한
        codePoint: 0xd55c,
        writingSystem: WritingSystem.Alphasyllabary,
        script: 'Hangeul',
        language: 'Korean',
    },
    glyph_4_p1: { // Й
        codePoint: 0x419,
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Russian',
    },
    glyph_4_p2: { // Ա
        codePoint: 0x531,
        writingSystem: WritingSystem.Alphabet,
        script: 'Armenian',
        language: 'Armenian',
    },
    glyph_4_p3: { // N
        codePoint: 0x4e,
        writingSystem: WritingSystem.Alphabet,
        script: 'Latin',
        language: 'English',
    },
    glyph_4_p4: { // ጨ
        codePoint: 0x1328,
        writingSystem: WritingSystem.Abugida,
        script: "Ge'ez",
        language: 'Harari',
    },
    glyph_4_p5: { // ळ
        codePoint: 0x933,
        writingSystem: WritingSystem.Abugida,
        script: 'Devanagari',
        language: 'Marathi',
    },
    glyph_4_p6: { // ཫ
        codePoint: 0xf6b,
        writingSystem: WritingSystem.Abugida,
        script: 'Tibetan',
        language: 'Lhasa Tibetan',
    },
    glyph_4_p7: { // Д
        codePoint: 0x414,
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Russian',
    },
    glyph_5_n7: { // 🤌
        codePoint: 0x1f90c,
        writingSystem: WritingSystem.Pictography,
        script: 'Emoji',
        language: null,
    },
    glyph_5_n6: { // 𑃤
        codePoint: 0x110e4,
        writingSystem: WritingSystem.Alphabet,
        script: 'Sorang Sompeng',
        language: 'Sora',
    },
    glyph_5_n5: { // ꕥ
        codePoint: 0xa565,
        writingSystem: WritingSystem.Syllabary,
        script: 'Vai',
        language: 'Vai',
    },
    glyph_5_n4: { // ঐ
        codePoint: 0x990,
        writingSystem: WritingSystem.Abugida,
        script: 'Bengali-Assamese',
        language: 'Assamese',
    },
    glyph_5_n3: { // Ѥ
        codePoint: 0x464,
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Old Church Slavonic',
    },
    glyph_5_n2: { // ß
        codePoint: 0xdf,
        writingSystem: WritingSystem.Alphabet,
        script: 'Latin',
        language: 'German',
    },
    glyph_5_n1: { // ઐ
        codePoint: 0xa90,
        writingSystem: WritingSystem.Abugida,
        script: 'Gujarati',
        language: 'Gujarati',
    },
    glyph_5_0: { // ⵣ
        codePoint: 0x2d63,
        writingSystem: WritingSystem.Alphabet,
        script: 'Tifinagh',
        language: 'Tashelhit',
    },
    glyph_5_p1: { // ࠀ
        codePoint: 0x800,
        writingSystem: WritingSystem.Abjad,
        script: "Samaritan",
        language: 'Samaritan Hebrew',
    },
    glyph_5_p2: { // Ꮞ
        codePoint: 0x13ce,
        writingSystem: WritingSystem.Syllabary,
        script: "Cherokee",
        language: "Cherokee",
    },
    glyph_5_p3: { // Ф
        codePoint: 0x424,
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Tajik',
    },
    glyph_5_p4: { // ꦖ
        codePoint: 0xa996,
        writingSystem: WritingSystem.Abugida,
        script: 'Javanese',
        language: 'Javanese',
    },
    glyph_5_p5: { // Э
        codePoint: 0x42d,
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Tuvan',
    },
    glyph_5_p6: { // أ
        codePoint: 0x623,
        writingSystem: WritingSystem.Abjad,
        script: 'Arabic',
        language: 'Farsi',
    },
    glyph_5_p7: { // 𖬕
        codePoint: 0x16b15,
        writingSystem: WritingSystem.Semisyllabary,
        script: 'Pahawh Hmong',
        language: 'Hmong Daw',
    },
    glyph_6_n7: { // ढ
        codePoint: 0x922,
        writingSystem: WritingSystem.Abugida,
        script: 'Devanagari',
        language: 'Hindi',
    },
    glyph_6_n6: { // 臣
        codePoint: 0x81e3,
        writingSystem: WritingSystem.Logosyllabary,
        script: 'Han',
        language: 'Mandarin',
    },
    glyph_6_n5: { // ꤎ
        codePoint: 0xa90e,
        writingSystem: WritingSystem.Alphabet,
        script: 'Kayah Li',
        language: 'Eastern Kayah',
    },
    glyph_6_n4: { // ꯄ
        codePoint: 0xabc4,
        writingSystem: WritingSystem.Abugida,
        script: 'Meitei',
        language: 'Manipuri',
    },
    glyph_6_n3: { // ሐ
        codePoint: 0x1210,
        writingSystem: WritingSystem.Abugida,
        script: "Ge'ez",
        language: 'Tigrinya',
    },
    glyph_6_n2: { // ზ
        codePoint: 0x10d6,
        writingSystem: WritingSystem.Alphabet,
        script: 'Georgian',
        language: 'Georgian',
    },
    glyph_6_n1: { // 𑣿
        codePoint: 0x118ff,
        writingSystem: WritingSystem.Alphabet,
        script: 'Warang Citi',
        language: 'Ho',
    },
    glyph_6_0: { // 𐓃
        codePoint: 0x104c3,
        writingSystem: WritingSystem.Alphabet,
        script: 'Osage',
        language: 'Osage',
    },
    glyph_6_p1: { // ฬ
        codePoint: 0xe2c,
        writingSystem: WritingSystem.Abugida,
        script: 'Thai',
        language: 'Thai',
    },
    glyph_6_p2: { // ח(hebrew)
        codePoint: 0x5d7,
        writingSystem: WritingSystem.Abjad,
        script: 'Hebrew',
        language: 'Hebrew',
    },
    glyph_6_p3: { // Đ
        codePoint: 0x110,
        writingSystem: WritingSystem.Alphabet,
        script: 'Latin',
        language: 'Vietnamese',
    },
    glyph_6_p4: { // 🌲
        codePoint: 0x1f332,
        writingSystem: WritingSystem.Pictography,
        script: 'Emoji',
        language: null,
    },
    glyph_6_p5: { // ಔ
        codePoint: 0xc94,
        writingSystem: WritingSystem.Abugida,
        script: 'Kannada',
        language: 'Kannada',
    },
    glyph_6_p6: { // ᦁ
        codePoint: 0x1981,
        writingSystem: WritingSystem.Abugida,
        script: 'New Tai Lue',
        language: 'Tai Lue',
    },
    glyph_6_p7: { // 𐴍
        codePoint: 0x10d0d,
        writingSystem: WritingSystem.Alphabet,
        script: 'Hanifi Rohingya',
        language: 'Rohingya',
    }
}