const WritingSystem = {
    Abugida: "Abugida",
    Alphabet: "Alphabet",
    Abjad: "Abjad",
    Syllabary: "Syllabary",
    Alphasyllabary: "Alphasyllabary",
    Logosyllabary: "Logosyllabary",
    Pictography: "Pictography"
}

export const glyphInfo = {
    glyph_0_n7: { // ఒ
        codePoint: 0x0C12,
        writingSystem: WritingSystem.Abugida,
        script: 'Telugu',
        language: 'Telugu',
    },
    glyph_0_n6: { // श
        codePoint: 0x0936,
        writingSystem: WritingSystem.Abugida,
        script: 'Devanagari',
        language: 'Nepali',
    },
    glyph_0_n5: { // ꊛ
        codePoint: 0xa29b,
        writingSystem: WritingSystem.Syllabary,
        script: 'Yi',
        language: 'Mantsi',
    },
    glyph_0_n4: { // R
        codePoint: 0x52,
        writingSystem: WritingSystem.Alphabet,
        script: 'Latin',
        language: 'Spanish',
    },
    glyph_0_n3: { // 😊
        codePoint: 0x1f60a,
        writingSystem: WritingSystem.Pictography,
        script: "Emoji",
        language: null,
    },
    glyph_0_n2: { // Я
        codePoint: 0x42f,
        writingSystem: WritingSystem.Alphabet,
        script: "Cyrillic",
        language: 'Bulgarian',
    },
    glyph_0_n1: { // ࠌ
        codePoint: 0x80c,
        writingSystem: WritingSystem.Abjad,
        script: "Samaritan",
        language: 'Samaritan Hebrew',
    },
    glyph_0_0: { // ฒ
        codePoint: 0xe12,
        writingSystem: WritingSystem.Abugida,
        script: 'Thai',
        language: 'Thai',
    },
    glyph_0_p1: { // ࡂ
        codePoint: 0x842,
        writingSystem: WritingSystem.Alphabet,
        script: 'Mandaic',
        language: 'Mandaic',
    },
    glyph_0_p2: { // キ
        codePoint: 0x30ad,
        writingSystem: WritingSystem.Syllabary,
        script: 'Katakana',
        language: 'Ainu',
    },
    glyph_0_p3: { // Л
        codePoint: 0x41b,
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Kyrgyz',
    },
    glyph_0_p4: { // ޝ
        codePoint: 0x79d,
        writingSystem: WritingSystem.Abugida,
        script: 'Thaana',
        language: 'Maldivian',
    },
    glyph_0_p5: { // რ
        codePoint: 0x10e0,
        writingSystem: WritingSystem.Alphabet,
        script: 'Georgian',
        language: 'Georgian',
    },
    glyph_0_p6: { // அ
        codePoint: 0xb85,
        writingSystem: WritingSystem.Abugida,
        script: 'Tamil',
        language: 'Tamil',
    },
    glyph_0_p7: { // H
        codePoint: 0x48,
        writingSystem: WritingSystem.Alphabet,
        script: 'Latin',
        language: 'Tok Pisin',
    },
    glyph_1_n7: { // ङ
        codePoint: 0x919,
        writingSystem: WritingSystem.Abugida,
        script: 'Devanagari',
        language: 'Newar',
    },
    glyph_1_n6: { // ถ
        codePoint: 0xe16,
        writingSystem: WritingSystem.Abugida,
        script: 'Thai',
        language: 'Tai Yo',
    },
    glyph_1_n5: { // ዑ
        codePoint: 0x12d1,
        writingSystem: WritingSystem.Abugida,
        script: "Ge'ez",
        language: 'Amharic',
    },
    glyph_1_n4: { // क
        codePoint: 0x915,
        writingSystem: WritingSystem.Abugida,
        script: 'Devanagari',
        language: 'Hindi',
    },
    glyph_1_n3: { // ဟ
        codePoint: 0x101f,
        writingSystem: WritingSystem.Abjad,
        script: 'Burmese',
        language: 'Burmese',
    },
    glyph_1_n2: { // ꚸ
        codePoint: 0xa6b8,
        writingSystem: WritingSystem.Syllabary,
        script: 'Bamum',
        language: 'Bamum',
    },
    glyph_1_n1: { // ᐊ
        codePoint: 0x140a,
        writingSystem: WritingSystem.Abugida,
        script: 'Qaniujaaqpait',
        language: 'Inuktitut',
    },
    glyph_1_0: { // ᐃ
        codePoint: 0x1403,
        writingSystem: WritingSystem.Abugida,
        script: 'Qaniujaaqpait',
        language: 'Inuktitut',
    },
    glyph_1_p1: { // ᐅ
        codePoint: 0x1405,
        writingSystem: WritingSystem.Abugida,
        script: 'Qaniujaaqpait',
        language: 'Inuktitut',
    },
    glyph_1_p2: { // উ
        codePoint: 0x989,
        writingSystem: WritingSystem.Abugida,
        script: 'Bengali',
        language: 'Bangla',
    },
    glyph_1_p3: { // 區
        codePoint: 0x5340,
        writingSystem: WritingSystem.Logosyllabary,
        script: 'Han',
        language: 'Cantonese',
    },
    glyph_1_p4: { // ܧ
        codePoint: 0x727,
        writingSystem: WritingSystem.Abjad,
        script: 'Syriac',
        language: 'Syriac',
    },
    glyph_1_p5: { // О̄
        codePoint: [0x41e, 0x304],
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Mansi',
    },
    glyph_1_p6: { // 𞋢
        codePoint: 0x1e2e2,
        writingSystem: WritingSystem.Alphabet,
        script: 'Wancho',
        language: 'Wancho',
    },
    glyph_1_p7: { // ひ
        codePoint: 0x3072,
        writingSystem: WritingSystem.Syllabary,
        script: 'Hiragana',
        language: 'Japanese',
    },
    glyph_2_n7: { // ⻩
        codePoint: 0x2ee9,
        writingSystem: WritingSystem.Logosyllabary,
        script: 'Han',
        language: 'Japanese',
    },
    glyph_2_n6: { // Ψ
        codePoint: 0x3a8,
        writingSystem: WritingSystem.Alphabet,
        script: 'Greek',
        language: 'Greek',
    },
    glyph_2_n5: { // 𖩏
        codePoint: 0x16a4f,
        writingSystem: WritingSystem.Alphabet,
        script: 'Mru',
        language: 'Mru',
    },
    glyph_2_n4: { // 𐒾
        codePoint: 0x104be,
        writingSystem: WritingSystem.Alphabet,
        script: 'Osage',
        language: 'Osage',
    },
    glyph_2_n3: { // む
        codePoint: 0x3080,
        writingSystem: WritingSystem.Syllabary,
        script: 'Hiragana',
        language: 'Japanese',
    },
    glyph_2_n2: { // ꂃ
        codePoint: 0xa083,
        writingSystem: WritingSystem.Syllabary,
        script: 'Yi',
        language: 'Nuosu',
    },
    glyph_2_n1: { // 语
        codePoint: 0x8bed,
        writingSystem: WritingSystem.Logosyllabary,
        script: 'Han',
        language: 'Mandarin',
    },
    glyph_2_0: { // 🤩
        codePoint: 0x1f929,
        writingSystem: WritingSystem.Pictography,
        script: 'Emoji',
        language: null,
    },
    glyph_2_p1: { // Å
        codePoint: 0xc5,
        writingSystem: WritingSystem.Alphabet,
        script: 'Latin',
        language: 'Swedish',
    },
    glyph_2_p2: { // Ҵ
        codePoint: 0x4b4,
        writingSystem: WritingSystem.Alphabet,
        script: 'Cyrillic',
        language: 'Abkhaz',
    },
    glyph_2_p3: { // 𑐂
        codePoint: 0x11402,
        writingSystem: WritingSystem.Abugida,
        script: 'Newa',
        language: 'Newar',
    },
    glyph_2_p4: { // 겅
        codePoint: 0xac85,
        writingSystem: WritingSystem.Alphasyllabary,
        script: 'Hangeul',
        language: 'Korean',
    },
    glyph_2_p5: { // 𐒌
        codePoint: 0x1048c,
        writingSystem: WritingSystem.Alphabet,
        script: 'Osmanya',
        language: 'Somali',
    },
    glyph_2_p6: { // ଞ
        codePoint: 0xb1e,
        writingSystem: WritingSystem.Abugida,
        script: 'Odia',
        language: 'Odia',
    },
    glyph_2_p7: { // ꂹ
        codePoint: 0xa0b9,
        writingSystem: WritingSystem.Syllabary,
        script: 'Yi',
        language: 'Nuosu',
    },
    glyph_2_p8: { // າ
        codePoint: 0xeb2,
        writingSystem: WritingSystem.Abugida,
        script: 'Lao',
        language: 'Lao',
    },
    glyph_3_n7: { // ਉ
        codePoint: 0xa09,
        writingSystem: WritingSystem.Abugida,
        script: 'Gurmukhi',
        language: 'Punjabi',
    },
    glyph_3_n6: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_n5: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_n4: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_n3: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_n2: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_n1: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_0: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_p1: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_p2: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_p3: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_p4: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_p5: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_p6: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_3_p7: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_n7: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_n6: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_n5: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_n4: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_n3: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_n2: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_n1: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_0: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_p1: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_p2: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_p3: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_p4: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_p5: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_p6: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_4_p7: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_n7: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_n6: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_n5: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_n4: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_n3: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_n2: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_n1: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_0: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_p1: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_p2: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_p3: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_p4: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_p5: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_p6: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_5_p7: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_n7: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_n6: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_n5: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_n4: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_n3: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_n2: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_n1: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_0: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_p1: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_p2: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_p3: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_p4: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_p5: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_p6: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    },
    glyph_6_p7: {
        codePoint: 0x0,
        writingSystem: '',
        script: '',
        language: '',
    }
}